//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Rent_a_Car.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class Araba
    {
        public int ID { get; set; }
        public string Plaka { get; set; }
        public string Marka { get; set; }
        public string Model { get; set; }
        public long Kilometre { get; set; }
        public int GunlukKMSinir { get; set; }
        public double GunlukFiyat { get; set; }
        public string Resim { get; set; }
        public string Aciklama { get; set; }
        public bool Airbag { get; set; }
        public Nullable<int> BagajHacmi { get; set; }
        public byte KoltukSayisi { get; set; }
        public string YakitTuru { get; set; }
        public string SanzimanTuru { get; set; }
    }
}
