//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Rent_a_Car.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class KiralamaIslemi
    {
        public int IslemID { get; set; }
        public int AracID { get; set; }
        public int MusteriID { get; set; }
        public System.DateTime KiralamaBaslangici { get; set; }
        public System.DateTime KiralamaBitisi { get; set; }
        public long BaslangicKM { get; set; }
        public Nullable<long> TeslimKM { get; set; }
        public double AlinanUcret { get; set; }
        public Nullable<bool> Durum { get; set; }
    }
}
