//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Rent_a_Car.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class Yonetici
    {
        public int ID { get; set; }
        public string TC { get; set; }
        public string Email { get; set; }
        public string Sifre { get; set; }
        public string Isim { get; set; }
        public string Soyisim { get; set; }
        public string Telefon { get; set; }
    }
}
